# Use an official lightweight Python image.
FROM python:3.10-slim

RUN apt-get update && apt-get install -y gcc default-libmysqlclient-dev pkg-config python3-dev curl
# Set the working directory in docker
WORKDIR /app

# Copy the content of the local src directory to the working directory
COPY ./src/ .
COPY ./db/ ../db
COPY ./tests/ ../tests

# Copy the dependencies file to the working directory
COPY tests/.coveragerc /app/.coveragerc
COPY .env.test /app/.env.test

# Install any dependencies
RUN pip install --no-cache-dir -r requirements/requirements.txt
RUN pip install --no-cache-dir -r ../tests/requirements/requirements.txt

COPY ./script/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Specify the command to run on container start
CMD ["pytest", "../tests"]
