"""create tables

Revision ID: 925d46178821
Revises:
Create Date: 2025-03-05 17:24:21.868643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '925d46178821'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('movie_code', sa.String(length=6), nullable=False, comment='映画コード'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='タイトル'),
    sa.Column('release_date', sa.Date(), nullable=False, comment='公開日'),
    sa.Column('recommendation', sa.Integer(), nullable=True, comment='おすすめ'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='削除日時'),
    sa.PrimaryKeyConstraint('movie_code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=15), nullable=False, comment='ユーザID'),
    sa.Column('user_name', sa.String(length=50), nullable=True, comment='ユーザ名'),
    sa.Column('email_address', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True, comment='メールアドレス'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('movies')
    # ### end Alembic commands ###
