name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'develop**'
      - main

env:
  MYSQL_USER: ${{secrets.MYSQL_USER}}
  MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}

jobs:
  ci:
    name: Run CI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests docker compose action
        run: |
          docker compose -f docker-compose.ci.yml run --rm --remove-orphans test

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage-artifact
          path: ./tests/htmlcov/*

#        uses: adambirds/docker-compose-action@v1.5.0
#        with:
#          compose-file: "./docker-compose.ci.yml"
#          up-flags: "--build"
#          down-flags: "--volumes"
#          test-container: "test"
#          test-command: "pytest ../tests --verbose --cov=routers --cov=cruds --cov-report=term-missing > ./pytest-coverage.txt"
