name: test

on:
  pull_request:
    branches:
      - 'develop**'

jobs:
  ci:
    name: Run CI tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env.test
        run: |
          echo "# Generate for GitHubActions Test." > .env.test
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env.test
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env.test
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env.test
          echo "MYSQL_HOST=${{ vars.MYSQL_HOST }}" >> .env.test
          echo "MYSQL_DATABASE=${{ vars.MYSQL_DATABASE }}" >> .env.test

      - name: Show .env.test file
        run: |
          echo '------------------------------------'
          cat .env.test
          echo '------------------------------------'

      - name: Run tests docker compose action
        run: |
          docker compose -f docker-compose.test.yml run --rm test
