name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MYSQL_USER: ${{secrets.MYSQL_USER}}
  MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
  MYSQL_HOST: ${{secrets.MYSQL_HOST}}
  MYSQL_PORT: ${{secrets.MYSQL_PORT}}
  MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-src.txt

      - name: Run tests in container
        run: docker compose up -d
