name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MYSQL_USER: ${{secrets.MYSQL_USER}}
  MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
  MYSQL_HOST: ${{secrets.MYSQL_HOST}}
  MYSQL_PORT: ${{secrets.MYSQL_PORT}}
  MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Run tests in container
#        run: docker compose up -d

      - name: Run tests docker compose action
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          comopse-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "test"
          test_command: "pytest ../tests --verbose --disable-warnings"
